config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'main/papers' => 'main#papers', :as => :papers
  get 'main/impressions' => 'main#first_impressions', :as => :impressions
  get 'main/offtopics' => 'main#offtopics', :as => :offtopics


  resources :entries

  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
  has_one :user
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  belongs_to :entry_type

  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :entry_type, presence: true
end

app/models/entry_type.rb
class EntryType < ApplicationRecord
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_one :user_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  layout "mainlayout"

  def new
    @entry = Entry.new
  end

  def create

    ap = article_params
    ap[:entry_type_id] = Integer(ap[:entry_type_id])
    ap[:user_id] = 1 #TODO CHANGE IF  WE HAVE MORE THAN 1 USER
    @entry = Entry.new(ap)

    if(@entry.save)
      redirect_to @entry
    else
      render 'new'
    end
  end

  def show
    @entry = Entry.find(params[:id])
  end

  private
  def article_params
    params.require(:entry).permit(:title, :abstract, :text, :link, :entry_type_id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout "mainlayout"
  def index
    @main_content =
    {
        "entries_type" => "all entries"
    }

    @entries = Entry.all().order("updated_at DESC")
  end

  def papers
    @main_content =
    {
        "entries_type" => "paper entries"
    }

    @entries = Entry.where(entry_type_id: "2")

    render 'index'
  end

  def first_impressions
    @main_content =
    {
        "entries_type" => "first impression entries"
    }

    @entries = Entry.where(entry_type_id: "1")

    render 'index'
  end

  def offtopics
    @main_content =
    {
        "entries_type" => "offtopic entries"
    }

    @entries = Entry.where(entry_type_id: "3")

    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/entries/new.html.erb
<hr>
<div class="d-flex justify-content-center"><h1>Creating an <strong>entry</strong></h1></div>
<hr>

<div class="container">
  <%= form_for :entry, url: entries_path do |f| %>
    <% if @entry.errors.any? %>
    <div style="color: #e53935;">
      <div id="error">
        <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this article from being saved:</h2>
      </div>

      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <p>
      <h2>Title</h2><br>
      <%= f.text_field :title %>
    </p>
    <br>

    <p>
      <h2>Abstract</h2><br>
      <%= f.text_area :abstract %>
    </p>
    <br>

    <p>
      <h2>Text</h2><br>
      <%= f.text_area :text %>
    </p>
    <br>

    <p>
      <h2>Download link (Can be null)</h2><br>
      <%= f.text_field :link %>
    </p>
    <br>

    <p>
      <h2>Entry type:
      <%= f.collection_select :entry_type_id, EntryType.all, :id, :name %></h2>
    </p>
    <br>
    <hr>

    <p>
      <div class="d-flex justify-content-center"><h1><%= f.submit :class => "btn btn-success custom-submit-btn"%></h1></div>
    </p>

  <% end %>
</div>

app/views/entries/show.html.erb
<div class="container wow fadeIn" data-wow-duration="2s">



  <div class="card text-xs-center">
    <% div = case @entry.entry_type.id
    when 2 then '<div class="card-header primary-color white-text">'
    when 1 then '<div class="card-header teal accent-3">'
    when 3 then '<div class="card-header secondary-color white-text">'
    when 4 then '<div class="card-header deep-orange darken-2 white-text">'
    else '<div class="card-header deep-orange darken-2 white-text">'
    end
    %>
    <%= raw div %>
        <h4 class="d-flex justify-content-center"><%= @entry.entry_type.name %></h4>
    </div>
    <div class="card-body">
        <br><h1 class ="d-flex justify-content-center"><%= @entry.title %></h1>
        <h4 class="d-flex justify-content-center">By <%= @entry.user.name %> <%= @entry.user.surname %></h4>
    </div>
  </div>
</div>


  <% if @entry.abstract != nil && @entry.abstract != "" %>
    <div class="container  wow fadeIn" data-wow-duration="2s">
      <br><h3><strong>Abstract</strong></h3><br>
      <%= raw @entry.abstract %>
    </div>
    <br><hr>
  <% end %>

  <% if @entry.text != nil && @entry.text != "" %>
    <br><br>
    <div class="container  wow fadeIn" data-wow-duration="2s">
      <%= raw @entry.text %>
    </div>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mainlayout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Erik Tordera's blog</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">


  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

  <!-- Include Editor style. -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_style.min.css" rel="stylesheet" type="text/css" />

  <%= stylesheet_link_tag "bootstrap.min" %>
  <%= stylesheet_link_tag "mdb.min" %>
  <%= stylesheet_link_tag "style" %>

  <%= yield :head %>
</head>

<body onresize="checkCollapse()">


    <div class="row">
      <div class="col-sm-3">

          <div class="navbar navbar-default fixed-top" role="navigation"  style="background-color:#1565c0;" id="global-navbar">
            <div class="navbar-header">


              <button type="button" class="navbar-toggle fa fa-bars btn btn-blue-grey btn-sm hidden-md-up" aria-hidden="true" data-toggle="collapse" data-target=".sidebar-navbar-collapse" id="toggleBtn">
                <span class="sr-only"> Toggle navigation </span>
              </button>

              <span class="d-flex justify-content-center" id="brand">
                <a class="navbar-brand navbar-link" href="/">
                  <div class="d-flex justify-content-center">
                    <div class="hexagon" id="avatar"><div class="hexTop"></div><div class="hexBottom"></div></div>
                  </div>
                  <span style="color: white;" id="brand-text"><strong>Erik Tordera Bermejo</strong></span>
                </a>
              </span>
            </div>

            <div class="navbar-collapse collapse sidebar-navbar-collapse padded-to-bot" id="navbar">
              <div class="d-flex flex-column" id="btns">
                <%= link_to :papers do %><div class="p-2 d-flex flex-row waves-effect waves-light" style="color: white;" id="btn-menu-2">Papers</div> <% end %>
                <%= link_to :impressions do %><div class="p-2 d-flex flex-row waves-effect waves-light" style="color: white;" id="btn-menu-3">First Impressions</div><% end %>
                <%= link_to :offtopics do %><div class="p-2 d-flex flex-row waves-effect waves-light" style="color: white;" id="btn-menu-3">Offtopics</div><% end %>
                <hr><a href="#">
                <a href="#"> <div class="p-2 d-flex flex-row waves-effect waves-light" id="btn-menu-4" style="color: white;">About me</div> </a>
              </div>
            </div>

          </div>
      </div>
      <div class="col-sm-9">
        <div class="container-fluid" id="text">
          <div class="row" id=main>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <%= javascript_include_tag "jquery-3.1.1.min" %>
  <!-- Bootstrap tooltips -->
  <%= javascript_include_tag "tether.min" %>
  <!-- Bootstrap core JavaScript -->
  <%= javascript_include_tag "bootstrap.min" %>
  <!-- MDB core JavaScript -->
  <%= javascript_include_tag "mdb.min" %>

  <%= javascript_include_tag "scripts" %>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

  <!-- Include Editor JS files. -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1//js/froala_editor.pkgd.min.js"></script>

  <!-- Initialize the editor. -->
  <script>
    new WOW().init()
    $(function() {
      $('textarea').froalaEditor(
        {
          height: 300
        }
      )
    });
  </script>



</body>
</html>

app/views/main/index.html.erb
<% if @entries.count > 0 %>
  <div class="col-12">
    <hr>
    <h1 class="d-flex justify-content-center"><%= @main_content["entries_type"].capitalize %></h1>
    <hr>
  </div>

        <% @entries.each do |entry| %>
            <div class="col-12 col-lg-12 animated wow fadeInUp" data-wow-duration="1.5s">
              <%= link_to(entry) do %>
              <div class="card waves-effect waves-light text-xs-center">
                <% div = case entry.entry_type.id
                when 2 then '<div class="card-header primary-color white-text">'
                when 1 then '<div class="card-header teal accent-3 black-text">'
                when 3 then '<div class="card-header secondary-color white-text">'
                when 4 then '<div class="card-header deep-orange darken-2 white-text">'
                else '<div class="card-header deep-orange darken-2 white-text">'
                end
                %>

                <% div2 = case entry.entry_type.id
                when 2 then '<div class="card-footer primary-color white-text">'
                when 1 then '<div class="card-footer teal accent-3 black-text">'
                when 3 then '<div class="card-footer secondary-color white-text">'
                when 4 then '<div class="card-footer deep-orange darken-2 white-text">'
                else '<div class="card-footer deep-orange darken-2 white-text">'
                end
                %>
                <%= raw div %>
                  <h4 class="d-flex justify-content-center"><%= entry.title %></h4>
                  <h6 class="d-flex justify-content-center">By <%= entry.user.name %> <%= entry.user.surname %></h6><hr>
                  <h6 class="d-flex justify-content-center"><%= entry.entry_type.name %></h6>
                </div>

                <% if entry.abstract != nil && entry.abstract != "" %>
                  <div class="card-body">
                    <p><div class ="d-flex justify-content-center black-text"><%= raw entry.abstract.first(480) %>...</p></div>
                  </div>
                <% end %>

              </div>
              <% end %>
            </div>
          <div class="col-12"><br><br></div>
        <% end %>
<% else %>
  <hr>
  <div class="d-flex justify-content-center"><h1> There is no <%= @main_content["entries_type"] %> entries at the time </h1></div>
  <hr>
<% end %>